version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  db:
    build: ./database
    volumes:
      - db_data:/var/lib/sqlite3

volumes:
  db_data:
